CREATE TABLE genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

ALTER TABLE genre
    ADD CONSTRAINT uc_genre_name UNIQUE (name);